# coding: utf-8

# flake8: noqa
"""
    Fonts API

    Everything Fonts Font API gives you API access to fonts, font properties and font tools. You can get all the details about font upto the individual glyph level and do amazing things with it. This is a first of its kind on the cloud. Font conversion API allows you to easily convert between various font formats using REST API. ttf,otf,svg,pfa,pfb, svg, woff,woff2, eot, ufo and several other formats are supported. Here are the individual API links:    ## Font Management API ##   All the things you need to manage a font on the cloud. [Click here to subscribe](https://everythingfonts.com/api/font)   ## @font-face generation API ##   Easily generate @font-face kit from variety of font formats. This service lets you generate ttf, otf, svg and woff formats that the browsers understand along with the relevant CSS definition. [Click here to subscribe](https://everythingfonts.com/api/ffgen)    ## Font Coversion API ##   Convert from one font format to another. Many many font format conversions are supported. [Click here to subscribe](https://everythingfonts.com/api/convert)   ## Font Subsetting API ##   Subset fonts easily. You can specify unicode range or individual characters for subsettings. [Click here to subscribe](https://everythingfonts.com/api/subset)   ## Font Hinting API ##   Font hinting on the cloud. Multiple hinting schemes supported. [Click here to subscribe](https://everythingfonts.com/api/hinting)   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.font_body import FontBody
