# coding: utf-8

"""
    Fonts API

    Everything Fonts Font API gives you API access to fonts, font properties and font tools. You can get all the details about font upto the individual glyph level and do amazing things with it. This is a first of its kind on the cloud. Font conversion API allows you to easily convert between various font formats using REST API. ttf,otf,svg,pfa,pfb, svg, woff,woff2, eot, ufo and several other formats are supported. Here are the individual API links:    ## Font Management API ##   All the things you need to manage a font on the cloud. [Click here to subscribe](https://everythingfonts.com/api/font)   ## @font-face generation API ##   Easily generate @font-face kit from variety of font formats. This service lets you generate ttf, otf, svg and woff formats that the browsers understand along with the relevant CSS definition. [Click here to subscribe](https://everythingfonts.com/api/ffgen)    ## Font Coversion API ##   Convert from one font format to another. Many many font format conversions are supported. [Click here to subscribe](https://everythingfonts.com/api/convert)   ## Font Subsetting API ##   Subset fonts easily. You can specify unicode range or individual characters for subsettings. [Click here to subscribe](https://everythingfonts.com/api/subset)   ## Font Hinting API ##   Font hinting on the cloud. Multiple hinting schemes supported. [Click here to subscribe](https://everythingfonts.com/api/hinting)   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FontBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'font': 'str'
    }

    attribute_map = {
        'font': 'font'
    }

    def __init__(self, font=None):  # noqa: E501
        """FontBody - a model defined in Swagger"""  # noqa: E501
        self._font = None
        self.discriminator = None
        self.font = font

    @property
    def font(self):
        """Gets the font of this FontBody.  # noqa: E501

        Font File to add to your collection  # noqa: E501

        :return: The font of this FontBody.  # noqa: E501
        :rtype: str
        """
        return self._font

    @font.setter
    def font(self, font):
        """Sets the font of this FontBody.

        Font File to add to your collection  # noqa: E501

        :param font: The font of this FontBody.  # noqa: E501
        :type: str
        """
        if font is None:
            raise ValueError("Invalid value for `font`, must not be `None`")  # noqa: E501

        self._font = font

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FontBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FontBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
